
```{r qbstat rating, echo=FALSE, warning=FALSE, message=FALSE}
#Load the Library

library(shiny)
library(ggplot2)
load(url("https://github.com/masaenz1/STA_6233_Spring2021/blob/main/Data_project_2/qbstatstotal.RData?raw=true"))

# Define UI for application that draws a histogram
ui <- fluidPage(
    # Application title
    titlePanel("Quarterback Stats- Quarterback Ratings per Season"),
    
    
    #Output: Type of plot
    mainPanel(
      plotOutput(outputId = "FreqTab") #Any name can go where "FreqTab" is, but be sure to keep it consistent with name in output$FreqTab in the server section
    )
  )

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$FreqTab <- renderPlot({
    # draw the histogram with the specified number of bins
    ggplot(qbstats, aes(x=YEAR, y=RTG)) + geom_bar(stat = "identity", fill="blue") + geom_text(aes(label = RTG), vjust = -0.2, size=3) + ylim(0, 110) +scale_x_continuous(breaks=c(2004,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020))  #Notice the difference between the ggplots
  })
}
# Run the application 
shinyApp(ui = ui, server = server)
```


###### **Summary data points for QB Ratigns** 
```{r summary RTG, eval=TRUE, echo=FALSE}    
# Sidebar layout
summary(qbstats$RTG)
```
Add text here that added details and information behind the QB Ratings percentage per season for the QBs
